<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cbp</string>
	</array>
	<key>name</key>
	<string>Command Block Parser</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>~?([+-]?\d+(\.\d+)?)|~</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*//.*$</string>
			<key>name</key>
			<string>comment.line.double-dash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\:\w+)(\s+)(CLOCK|PULSE|DELAY)(\s+)(?=(\d\s\d\s\d))</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^(\bDEFINE\b|\bUNDEFINE\b|\bSET\b|\bUNSET\b|\bIF\b|\bFUNC\b|\bLOOP\b|\bEND\b|\bUSE\b|\bUNUSE\b|\bCONSTART\b|\bCONEND\b|\bCONDITION\b)(\s|$)|^\bIMPORT\b\s)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([&lt;&gt;]=?|\*|-|\+|\|)|=</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\bSIN|\bCOS|\bTAN|\bCEIL|\bFLOOR|\bSQRT|\bROUND|\bPOW|\bMUL|\bDIV|\bADD|\bSUB|\bMOD|\bAND|\bOR|\bNOT|\bGRTR|\bSMLR|\bEQL|\bINT|\bGROUP_VAL|\bNBT_SET|\bNBT_REMOVE|\bESCAPE|\bCALC|\bDEF_VALUE|\bPARSE)(?=\((.*)\))</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\bgamemode\b|\bentitydata\b|\bgive\b|\bscoreboard\b|\bstats\b|\btp\b|\bworldborder\b|\bkill\b|\bspreadplayers\b|\bxp\b|\bdifficulty\b|\bdebug\b|\bgamerule\b|\bclear\b|\bparticle\b|\btitle\b|\btime\b|\bhelp\b|\bdefaultgamemode\b|\bweather\b|\bme\b|\btell\b|\bpublish\b|\breplaceitem\b|\bclone\b|\btrigger\b|\bexecute\b|\bachievement\b|\btellraw\b|\btestforblock\b|\bseed\b|\bfill\b|\bblockdata\b|\bplaysound\b|\bmsg\b|\bspawnpoint\b|\bsetblock\b|\bw\b|\btoggledownfall\b|\beffect\b|\btestforblocks\b|\bsetworldspawn\b|\bsay\b|\bsummon\b|\btestfor\b|\benchant)(\s|$)</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>minecraft:\w+</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[apre]</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\w_]+(?=(&lt;|&gt;)*=(&lt;|&gt;)*[!\w_])</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;==|=!)[(\w|\d)*_]+</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>false|true</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+,\d+,\d+,?</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"([^"\\]*(\\.)*)*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.command_block_parser</string>
	<key>uuid</key>
	<string>4df609d0-76a7-4781-b306-317feeb61b2e</string>
</dict>
</plist>
